#server:
#  port: 7080

#spring:
#  jdbc:
#    datasource:
#      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql:///springboot_01
#      username: root
#      password: root
spring:
  profiles:
    active: datasource

